"""
Tool 4 – Report Writer Tool  (Student 4 contribution)

Takes structured analysis data and writes a human-readable Markdown
financial report to disk.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Dict

import crewai_bootstrap  # noqa: F401
from crewai.tools import tool

from config import OUTPUT_DIR
from observability.logger import AgentLogger
from state.global_state import GlobalState

_logger = AgentLogger("report_writer_tool")


def _build_markdown(data: Dict[str, Any]) -> str:
    """Render a Markdown report from the combined analysis data."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Personal Finance Report",
        f"*Generated on {now}*\n",
        "---\n",
    ]

    budget = data.get("budget", {})
    summary = data.get("spending_summary", {})
    recommendations = data.get("recommendations", [])

    if budget:
        lines.append("## Budget Overview\n")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Monthly Income | ${budget.get('monthly_income', 0):,.2f} |")
        lines.append(f"| Total Spent | ${budget.get('total_spent', 0):,.2f} |")
        remaining = budget.get("monthly_income", 0) - budget.get("total_spent", 0)
        lines.append(f"| Remaining | ${remaining:,.2f} |")
        lines.append("")

    if budget.get("targets"):
        lines.append("## 50/30/20 Budget Analysis\n")
        lines.append("| Category | Target | Actual | Difference |")
        lines.append("|----------|--------|--------|------------|")
        targets = budget.get("targets", {})
        actuals = budget.get("actuals", {})
        diffs = budget.get("differences", {})
        for key in ["needs", "wants", "savings"]:
            t = targets.get(key, 0)
            a = actuals.get(key, diffs.get(key, 0))
            d = diffs.get(key, 0)
            status = "+" if d >= 0 else ""
            lines.append(f"| {key.title()} | ${t:,.2f} | ${a:,.2f} | {status}${d:,.2f} |")
        lines.append("")

    if summary:
        lines.append("## Spending by Category\n")
        lines.append("| Category | Amount | Transactions |")
        lines.append("|----------|--------|-------------|")
        for cat, info in sorted(summary.items()):
            if cat.startswith("_"):
                continue
            lines.append(f"| {cat.title()} | ${info.get('total', 0):,.2f} | {info.get('count', 0)} |")
        lines.append("")

    if recommendations:
        lines.append("## Recommendations\n")
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"{i}. {rec}")
        lines.append("")

    lines.append("---\n*Report generated by the Personal Finance Advisor Multi-Agent System*\n")
    return "\n".join(lines)


@tool("report_writer_tool")
def report_writer_tool(analysis_json: str) -> str:
    """Generate a Markdown financial report and save it to disk.

    Accepts the combined analysis output (budget, spending summary,
    recommendations) as a JSON string and writes a formatted Markdown
    report to the output directory.

    Args:
        analysis_json: JSON string containing keys 'budget',
            'spending_summary', and 'recommendations'.

    Returns:
        A confirmation message with the file path of the generated report.
    """
    state = GlobalState()

    try:
        data: Dict[str, Any] = json.loads(analysis_json)
    except json.JSONDecodeError as exc:
        error_msg = f"Invalid JSON input: {exc}"
        _logger.log_tool_call("report_writer_tool", {}, error_msg, success=False, error=error_msg)
        return error_msg

    markdown = _build_markdown(data)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"finance_report_{timestamp}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)

    try:
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(markdown)
    except OSError as exc:
        error_msg = f"Failed to write report: {exc}"
        _logger.log_tool_call("report_writer_tool", {"filepath": filepath}, error_msg, success=False, error=error_msg)
        return error_msg

    state.set("report_path", filepath, agent_name="ReportGeneratorAgent")
    _logger.log_tool_call(
        "report_writer_tool",
        {"filepath": filepath},
        f"Report written ({len(markdown)} chars)",
    )
    _logger.log_state_update("report_path", filepath)

    return f"Report successfully written to: {filepath}\n\nReport preview:\n{markdown[:1000]}"
